# Generated by Django 5.2.7 on 2025-10-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Messages',
        ),
    ]
